### PR TITLE
Content

### PR DESCRIPTION
**Pull request by tzvaita**
Project #3 done.

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @tzvaita and @didymus707 :wave: 

You guys are doing well; keep this spirit high :+1:. Your project is good so far but require some changes.

**Navigation bar**
- [ ] It has a "Hamburger button", a search icon and **a link with text** on the leftmost side. _(The text has to be a link)_

**Others**
- [ ] Files not related to the project should not be committed and added to `.gitignore` _(What exactly is `.editorconfig` doing for us in this repo? :wink: )_ 

**Kindly submit another code review request after making those fixes**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by Forison — COMMENTED** [review]
# pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi team👋 
### Good work on implementing the changes mentioned earlier in the first review.
#### Go ahead and merge to master
## Project is approved💪
### Happy coding😇

**Comment by tzvaita** [comment]
Done the changes as per second review

**Pull request merged**
